### ISSUE TITLE
/r/video/search not working

### ISSUE THREAD

**Issue by fallenangel2305** [Swag666baby/nsfw-api#1]
/r/video/search?q=<your_research>

whiteporn cdn now has a token for the api

**Comment by fallenangel2305** [comment]
https://rapidapi.com/barcalover017/api/porn-videos

maybe you can use this api

**Comment by Swag666baby** [comment]
> /r/video/search?q=<your_research>
> 
> whiteporn cdn now has a token for the api

here the route is working perfectly. It's very slow, but it responds correctly
