### ISSUE TITLE
New Issue #1

### ISSUE THREAD

**Issue by kakashihatake2006** [Swag666baby/nsfw-api#3]
Hello Sir Actually There is  a problem The hentai image search Section from rule 34 is Fetching thumbnails  which aren't good quality one can u update that to good quality  for example :- 
 https://us.rule34.xxx//images/19/7890efab346a7d74e0cd9ac14e185718a5fa2f05.jpg?18158

**Comment by Swag666baby** [comment]
thanks for the observation. this has just been fixed.
